# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.boot_timeout = 600
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  
  #configure provisioners on the machine
  config.vm.provision :docker 

  config.vm.define "server-1" do |dockerserver|
    dockerserver.vm.network "private_network", ip: '192.168.33.60'
    dockerserver.vm.hostname = "dockerserver"
    config.vm.provision :docker_compose, yml: "/vagrant/AT19_DOCKER-COMPOSE/docker-compose.yml", rebuild: true, run: "always"
  end
end